const jwt = require('jsonwebtoken');

// Middleware is just a function that receive the welknown arguments req, res, next
// that validates if the request should continue or not.

// 1. check if there is a token
// 2. validate the token
module.exports = (req, res, next) => {

  // try will try to split the token
  try {
    // gets the token from the request Header.
    const token = req.headers.authorization.split(" ")[1]; // removing the "Bearer" word from the token string

    // checking if the token is valid. if it was generated by this server wth this secret
    jwt.verify(token, 'asdhkYSJHASs87s7jhgsa768JHGajhg&62j!==');

    // let the execution continue
    next();

  } catch (error) { //if fails to split the token, there was no token, or wrong format
    res.status(401).json({
      message: 'Auth failed. No token sent.'
    });
  }
}
